"""Which calendar days each venue actually trades.

Tarzan decides "the previous session", "n sessions back" and "the last close
on-or-before a cutoff" in four places — the trailing-window anchors
(:mod:`tarzan.engine.stats`), the current-session stamp
(:mod:`tarzan.data.current_session`), and the daily tail fill
(``enricher._is_previous_trading_day``). All four used a Mon–Fri rule and each
carried its own ``ponytail:`` note saying holidays were not modelled, which made
a window slide by one session around every exchange holiday (~6–17 days a year
depending on the venue). This is the one table all of them read.

The data is VENDORED rather than computed at run time, the same way the UEQC
carry index and the Fama-French factor series are. Two reasons:

* a pinned ``--as_of`` run must be byte-reproducible, and a calendar library's
  holiday data changes between releases — vendoring makes the calendar part of
  the repository, not of the environment;
* it costs no runtime dependency: 18 venues over nine years is 3.7 KB gzipped.

Generated by ``scripts/refresh_exchange_holidays.py`` from
``exchange_calendars`` 4.13.2 (a generation-time dependency only, never
installed for a run). That library bounds itself about a year into the future,
so the table does too — see :func:`covers`, which is why every lookup degrades
to the weekday rule beyond the horizon instead of silently reading an unknown
future date as a trading day. Re-run the generator to extend it.

Half-days are modelled too, in the ``close`` column: an early close IS a session,
so it changes no date question asked here, but the hours table in
``market_quotes._SESSIONS`` holds one fixed close per venue group and therefore
called the exchange open for the hours after it had shut. 157 of them across twelve
venues — the US day after Thanksgiving and Christmas Eve are the familiar ones, and
London, Paris, Dublin, Hong Kong and Sydney have their own. See
:func:`session_close`.
"""

from __future__ import annotations

import datetime
import logging
from functools import lru_cache
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_BUNDLED = Path(__file__).resolve().parent / "exchange_holidays.csv.gz"

# Yahoo listing suffix → ISO 10383 MIC. Deliberately finer than
# ``market_quotes._SUFFIX_EXCHANGE``, whose groups share trading HOURS but not
# holidays: Milan and Xetra both trade 09:00–17:30 CET, yet Milan closes for the
# Assumption on 15 August and Xetra does not. Hours are a session-shape question
# and stay in that table; holidays are a per-exchange question and live here.
_SUFFIX_MIC: dict[str, str] = {
    "MI": "XMIL", "ETLX": "XMIL",          # Borsa Italiana (incl. EuroTLX)
    "DE": "XETR", "F": "XETR",             # Xetra / Frankfurt
    "PA": "XPAR", "AS": "XAMS", "BR": "XBRU", "LS": "XLIS", "MC": "XMAD",
    "VI": "XWBO", "SW": "XSWX", "HE": "XHEL", "IR": "XDUB",
    "L": "XLON",
    "SS": "XSHG", "SZ": "XSHG", "HK": "XHKG", "T": "XTKS",
    "AX": "XASX", "KS": "XKRX",
    # The German regional/retail venues keep their own 08:00–22:00 hours but
    # follow the German trading calendar for which DAYS they are open.
    "MU": "XETR", "SG": "XETR", "BE": "XETR", "DU": "XETR",
    "HM": "XETR", "HA": "XETR", "TG": "XETR",
}

# ``market_quotes`` exchange group → MIC, for the symbols it maps by group
# rather than by suffix (indices such as ^GSPC, and bare tickers a curated
# taxonomy promotes to a venue).
_GROUP_MIC: dict[str, str] = {
    "EU": "XMIL", "L": "XLON", "US": "XNYS", "JP": "XTKS", "HK": "XHKG",
    "CN": "XSHG", "AU": "XASX", "KR": "XKRX", "DE_REG": "XETR",
    "HE": "XHEL", "IR": "XDUB",
}

# Indices whose own venue is NOT the one their exchange group resolves to.
# ``_exchange_for`` files every continental European symbol under "EU", which
# _GROUP_MIC sends to Milan — fine for a Milan-listed ETF, wrong for the DAX and
# the CAC, which follow Frankfurt's and Paris' holidays. The three calendars
# genuinely differ (Milan trades 6 Jan and Frankfurt does not; Frankfurt shuts
# 24 and 31 Dec and Milan does not), so without this the markets strip would
# state a German index open on a German holiday and shut on an Italian one.
_INDEX_MIC: dict[str, str] = {
    "^GDAXI": "XETR", "^FCHI": "XPAR", "^N100": "XPAR", "^STOXX50E": "XETR",
}


@lru_cache(maxsize=1)
def _table() -> tuple[dict[str, frozenset], dict[str, tuple], dict[str, dict]]:
    """``({mic: {closed weekdays}}, {mic: (first, last)}, {mic: {date: (h, m)}})``.

    The third element is the EARLY CLOSES: a short session is still a session, so
    it is absent from the closure set, and a reader holding one fixed close per
    venue therefore called the exchange open for the hours after it had shut. The
    time is the venue's own wall clock, the same units the session-hours table
    uses.

    Empty on any failure: a missing or corrupt table degrades every caller to the
    Mon–Fri rule, which is what they all did before this existed. A table written
    before the ``close`` column existed still reads correctly — every row simply
    has no close, which is what a closure means.
    """
    try:
        import pandas as pd

        frame = pd.read_csv(_BUNDLED, dtype=str)
        closes = (frame["close"] if "close" in frame.columns
                  else [None] * len(frame))
        closed: dict[str, set] = {}
        early: dict[str, dict] = {}
        for mic, date, close in zip(frame["mic"], frame["date"], closes):
            mic, day = str(mic), datetime.date.fromisoformat(str(date))
            text = "" if close is None else str(close).strip()
            if text and text.lower() != "nan":
                hh, _, mm = text.partition(":")
                early.setdefault(mic, {})[day] = (int(hh), int(mm))
            else:
                closed.setdefault(mic, set()).add(day)
        # The horizon is per MIC: each source calendar bounds itself, and a
        # lookup past that bound is unknown, not "open". An early close is a
        # dated fact from the same source, so it counts towards the span.
        spans = {}
        for mic in set(closed) | set(early):
            days = closed.get(mic, set()) | set(early.get(mic, {}))
            spans[mic] = (min(days), max(days))
        return ({mic: frozenset(days) for mic, days in closed.items()},
                spans, early)
    except Exception as exc:  # noqa: BLE001 — never break a run over a calendar
        logger.warning(
            "exchange holiday table unavailable (%s); every session question "
            "falls back to the Mon-Fri rule", exc)
        return ({}, {}, {})


def session_close(ticker: str, day: datetime.date) -> Optional[tuple[int, int]]:
    """``(hour, minute)`` of an EARLY close for ``ticker`` on ``day``, else None.

    None means "the venue's regular hours apply", which is also the honest answer
    for a date outside the vendored horizon or a venue the table does not know.
    """
    mic = venue_mic(ticker)
    if mic is None:
        return None
    _, _, early = _table()
    return (early.get(mic) or {}).get(day)


@lru_cache(maxsize=2048)
def venue_mic(ticker: str) -> Optional[str]:
    """The MIC whose holiday calendar governs ``ticker``, or None if unknown.

    Cached because this is a hot path and the miss is expensive: resolving a
    suffixless symbol goes through ``market_quotes._exchange_for``, which asks
    the curated taxonomy, which rebuilds a record list per call. Every window of
    every instrument asks for this, and the answer is a pure function of the
    symbol.
    """
    text = str(ticker or "").strip().upper()
    if not text:
        return None
    # Before the group fallback: an index carries no suffix, so it would
    # otherwise be resolved by exchange group and land on the wrong calendar.
    mic = _INDEX_MIC.get(text)
    if mic:
        return mic
    if "." in text:
        mic = _SUFFIX_MIC.get(text.rsplit(".", 1)[1])
        if mic:
            return mic
    try:
        from tarzan.data.market_quotes import _exchange_for

        group = _exchange_for(text)
    except Exception:  # noqa: BLE001 — resolution must fail conservatively
        group = None
    return _GROUP_MIC.get(group) if group else None


def _covers_mic(mic: Optional[str], day: datetime.date) -> bool:
    if mic is None:
        return False
    _, spans, _early = _table()
    span = spans.get(mic)
    if span is None:
        return False
    # A year of slack past the last KNOWN closure: the table lists closures, so
    # its last entry is the final holiday, not the final covered day.
    return span[0] <= day <= (span[1] + datetime.timedelta(days=365))


def _is_session_mic(mic: Optional[str], day: datetime.date) -> bool:
    if day.weekday() >= 5:
        return False
    if mic is None or not _covers_mic(mic, day):
        return True
    closed, _, _early = _table()
    return day not in closed.get(mic, frozenset())


def _last_session_mic(mic: Optional[str], day: datetime.date) -> datetime.date:
    probe = day
    for _ in range(15):          # a fortnight covers the longest market closure
        if _is_session_mic(mic, probe):
            return probe
        probe -= datetime.timedelta(days=1)
    return probe


def covers(ticker: str, day: datetime.date) -> bool:
    """Whether the vendored table can answer for this venue on this date.

    False means "unknown", not "open": the caller keeps the weekday rule. The
    horizon is bounded a little over a year ahead because the source calendars
    are, so this goes False for far-future dates rather than asserting that an
    unlisted day traded.
    """
    return _covers_mic(venue_mic(ticker), day)


def is_session(ticker: str, day: datetime.date) -> bool:
    """Whether ``ticker``'s exchange trades on ``day``.

    Weekends are never sessions. Within the vendored horizon a listed closure is
    honoured; outside it, any weekday is treated as a session — the behaviour
    every caller had before this module existed.
    """
    return _is_session_mic(venue_mic(ticker), day)


def last_session_on_or_before(ticker: str, day: datetime.date) -> datetime.date:
    """``day`` itself when it is a session, else the most recent one before it.

    This is the rule every trailing window is anchored on, and the one Yahoo's
    own figures use: verified on XMME.MI, whose published 1M on 18 Aug 2026
    (+2.55%) is reproducible only from Friday 17 July, the session before that
    window's Saturday cutoff — not from the Monday after it (+1.13%).
    """
    return _last_session_mic(venue_mic(ticker), day)


def previous_session(ticker: str, day: datetime.date) -> datetime.date:
    """The session immediately before ``day`` (never ``day`` itself)."""
    return _last_session_mic(
        venue_mic(ticker), day - datetime.timedelta(days=1))


def sessions_back(ticker: str, day: datetime.date, count: int) -> datetime.date:
    """Step ``count`` sessions back from the last session on-or-before ``day``.

    ``count=0`` is that session itself, so a five-session window is
    ``sessions_back(ticker, end, 4)`` — the same "five sessions including today"
    span Yahoo's 5D covers.

    Resolves the venue ONCE and walks with it, rather than re-resolving per
    step: the resolution can reach the curated taxonomy, and a five-session walk
    asking for it up to seventy-five times is what turned a 40-second test suite
    into a 70-minute one.
    """
    mic = venue_mic(ticker)
    probe = _last_session_mic(mic, day)
    for _ in range(max(0, count)):
        probe = _last_session_mic(mic, probe - datetime.timedelta(days=1))
    return probe
