"""Convert a Fineco "Lista Titoli" movements export into a Tarzan
order-list CSV.

This step is **optional**. The main pipeline (``python -m tarzan.main``)
does not consume ``order_list.csv`` yet — it is the data source for
upcoming time-weighted return (TWROR) and money-weighted return
(XIRR) computations. The file is also designed to be the long-term
single source of truth for the portfolio: holdings (current
positions, cost basis) can be reconstructed from the orders by
aggregating quantities per ISIN.

Usage:
    python scripts/preprocess_orders.py
    python scripts/preprocess_orders.py \
        --input input/fineco_raw/Lista\\ Titoli.xlsx \
        --output input/order_list.csv

The Fineco "Lista Titoli" export carries three operation kinds:

  * "Compravendita titoli"        — buys (Segno=A) and sells (Segno=V).
  * "Stacco Cedole"               — bond coupons.
  * "Carico Trasferimento Titoli" — incoming security transfers from
    another broker. Some come with a small EUR figure (accrued
    coupons paid by the previous broker on transfer day) — those are
    emitted as a separate ``coupon`` row so the position transfer
    stays a clean cash-flow-zero event.

The output schema is intentionally richer than what TWROR/XIRR
strictly need today, so the file can later replace ``holdings.csv``
without a second migration:

    date         (YYYY-MM-DD)  settlement / value date — the date the
                               cash hits the account, used by XIRR.
    trade_date   (YYYY-MM-DD)  order date — useful for audit, can equal
                               ``date`` for non-trade events.
    type                       enum: buy, sell, coupon, dividend,
                               transfer_in, transfer_out.
    isin
    name                       Fineco-style description.
    ticker                     left blank — Fineco does not carry it
                               on this export; downstream code can
                               look it up from holdings.csv by ISIN.
    quantity                   signed: + for buy / transfer_in,
                               - for sell / transfer_out, 0 for
                               coupons and dividends.
    currency                   trade currency (EUR / USD / ...).
    price_native               unit price in trade currency.
    fx_rate                    EUR per unit of trade currency on the
                               trade day (1.0 for EUR trades).
    gross_eur                  signed gross EUR amount before fees.
    fees_eur                   sum of all fee columns (sw/ingr,
                               banca, sgr, amministrato).
    net_eur                    signed cash flow on the bank account:
                                 buy        → -(gross + fees)
                                 sell       → +(gross - fees)
                                 coupon     → +amount
                                 dividend   → +amount
                                 transfer_* → 0 (no cash movement)
    source                     "fineco" for rows generated by this
                               preprocessor; reserved for future
                               manual additions.

A timestamped backup of the destination file is always written
before the new file is created.
"""

from __future__ import annotations

import argparse
import csv
import logging
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd

# Ensure the tarzan package is importable when run from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tarzan.data.bond_fetcher import looks_like_bond_from_orders  # noqa: E402


logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("preprocess_orders")


ORDER_COLUMNS = [
    "date", "trade_date", "type", "isin", "name", "ticker",
    "quantity", "currency", "price_native", "fx_rate",
    "gross_eur", "fees_eur", "net_eur", "source",
]

# Italian column names from the Fineco "Lista Titoli" sheet.
FINECO_COLUMNS = [
    "Operazione", "Data valuta", "Descrizione", "Titolo", "Isin",
    "Segno", "Quantita", "Divisa", "Prezzo", "Cambio", "Controvalore",
    "Commissioni Fondi Sw/Ingr/Uscita",
    "Commissioni Fondi Banca Corrispondente",
    "Spese Fondi Sgr",
    "Commissioni amministrato",
]

FEE_COLUMNS = [
    "Commissioni Fondi Sw/Ingr/Uscita",
    "Commissioni Fondi Banca Corrispondente",
    "Spese Fondi Sgr",
    "Commissioni amministrato",
]


def _read_fineco_orders(path: Path) -> pd.DataFrame:
    """Read the Fineco movements export and return a tidy DataFrame.

    The Fineco file is structured like the holdings export: two
    header banner rows, a column-name row that we anchor on by
    looking for the "Operazione" cell, then the data rows.
    """
    raw = pd.read_excel(path, sheet_name=0, header=None)

    header_row = None
    for i, row in raw.iterrows():
        if any(str(cell).strip() == "Operazione" for cell in row):
            header_row = i
            break
    if header_row is None:
        raise RuntimeError(
            "Could not find the 'Operazione' header in the Fineco movements "
            "export — did the file format change?"
        )

    headers = [str(c).strip() for c in raw.iloc[header_row].tolist()]
    data = raw.iloc[header_row + 1:].copy()
    data.columns = headers

    # Keep only the columns we know about. Missing columns are
    # tolerated (filled with NA) so partial Fineco templates still
    # work, but ``Isin`` and ``Operazione`` are required.
    for required in ("Isin", "Operazione", "Descrizione"):
        if required not in data.columns:
            raise RuntimeError(
                f"Fineco movements export is missing the {required!r} column."
            )
    available = [c for c in FINECO_COLUMNS if c in data.columns]
    data = data[available].copy()

    # Drop rows whose ISIN is empty (banner / footer artefacts) or
    # whose date is unreadable.
    data["Isin"] = data["Isin"].astype(str).str.strip()
    is_isin = data["Isin"].str.match(r"^[A-Z0-9]{12}$", na=False)
    dropped = (~is_isin).sum()
    if dropped:
        logger.info("Skipped %d non-order row(s) in the Fineco export.", dropped)
    data = data[is_isin].reset_index(drop=True)

    return data


def _to_float(s: pd.Series) -> pd.Series:
    """Coerce a column to float, treating empty strings and ``NaN``
    as 0. Fineco sometimes exports fees as blank cells when no fee
    was charged; we want those to read as 0 rather than NaN so the
    ``fees_eur`` total stays well-defined.
    """
    return pd.to_numeric(s, errors="coerce").fillna(0.0)


def _parse_date(s: pd.Series) -> pd.Series:
    """Parse a Fineco DD/MM/YYYY date column into pandas Timestamps."""
    return pd.to_datetime(s, format="%d/%m/%Y", errors="coerce")


def _classify(row: pd.Series) -> Optional[str]:
    """Return the Tarzan ``type`` value for a Fineco row.

    ``None`` means "skip this row" — used for unrecognised
    Descrizione values, so a future Fineco extension does not
    silently corrupt the output.
    """
    desc = str(row.get("Descrizione", "")).strip().lower()
    if desc.startswith("compravendita"):
        sign = str(row.get("Segno", "")).strip().upper()
        if sign == "A":
            return "buy"
        if sign == "V":
            return "sell"
        return None
    if "cedole" in desc:
        return "coupon"
    if "trasferimento" in desc:
        return "transfer_in"
    return None


def _build_rows(fineco: pd.DataFrame) -> list[dict]:
    """Translate a Fineco DataFrame into normalised order dicts."""
    rows: list[dict] = []
    skipped: dict[str, int] = {}

    fineco["trade_dt"] = _parse_date(fineco["Operazione"])
    fineco["value_dt"] = _parse_date(fineco["Data valuta"])
    # Some events (coupons, transfers) only have one of the two
    # dates filled. Use whichever is available, preferring the
    # value date for cash-flow purposes.
    fineco["value_dt"] = fineco["value_dt"].fillna(fineco["trade_dt"])
    fineco["trade_dt"] = fineco["trade_dt"].fillna(fineco["value_dt"])

    for col in ("Quantita", "Prezzo", "Cambio", "Controvalore"):
        if col in fineco.columns:
            fineco[col] = _to_float(fineco[col])
    fineco["fees_eur"] = sum(
        (_to_float(fineco[c]) for c in FEE_COLUMNS if c in fineco.columns),
        start=pd.Series(0.0, index=fineco.index),
    )
    fineco["Divisa"] = fineco.get("Divisa", "EUR").astype(str).str.strip().str.upper()

    for _, r in fineco.iterrows():
        op_type = _classify(r)
        if op_type is None:
            key = str(r.get("Descrizione", "?")).strip()
            skipped[key] = skipped.get(key, 0) + 1
            continue

        date = r["value_dt"]
        trade_date = r["trade_dt"]
        if pd.isna(date):
            skipped["missing_date"] = skipped.get("missing_date", 0) + 1
            continue

        qty_raw = float(r.get("Quantita", 0.0) or 0.0)
        gross = float(r.get("Controvalore", 0.0) or 0.0)
        fees = float(r["fees_eur"] or 0.0)
        price = float(r.get("Prezzo", 0.0) or 0.0)
        fx = float(r.get("Cambio", 1.0) or 1.0) or 1.0
        currency = str(r.get("Divisa", "EUR") or "EUR")

        # Sign conventions per type. ``quantity`` is signed with the
        # direction of the position change (so summing per ISIN
        # gives the current holding); ``net_eur`` is signed with the
        # cash-flow direction on the bank account (positive = cash
        # in, negative = cash out).
        if op_type == "buy":
            quantity = abs(qty_raw)
            gross_eur = abs(gross)
            net_eur = -(gross_eur + fees)
        elif op_type == "sell":
            quantity = -abs(qty_raw)
            gross_eur = abs(gross)
            net_eur = +(gross_eur - fees)
        elif op_type == "coupon" or op_type == "dividend":
            # Quantity field on coupon rows carries the bond face
            # value, not a position delta — clear it so the row
            # cannot accidentally be aggregated into a holding.
            quantity = 0.0
            gross_eur = abs(gross)
            net_eur = +gross_eur
        elif op_type == "transfer_in":
            # A transfer carries the security itself, so it is
            # cash-flow zero from the bank account's perspective.
            # However Fineco does record the transfer price (column
            # ``Prezzo``) — that's the principal value the previous
            # broker reported, used for tax cost-basis purposes and
            # the closest thing to a market valuation we have at
            # transfer date.
            #
            # We compute ``gross_eur`` here so downstream consumers
            # (TWROR / XIRR) do not have to re-classify bonds vs
            # equities themselves. The convention:
            #
            #   * ``Prezzo`` between 50 and 150 with ``Quantita`` ≥
            #     1,000 → bond (clean price quoted per 100 face).
            #     EUR value = qty × price / 100 / fx.
            #   * Otherwise → equity / ETF (unit price).
            #     EUR value = qty × price / fx.
            #
            # The threshold is empirical but robust: ETF unit prices
            # in the 50-150 range come with retail quantities (a few
            # tens to a few hundreds), while bond face values are
            # always ≥ 1,000 in practice. Fineco itself never sets
            # ``Prezzo`` to a value outside the bond range for a
            # bond, so the misclassification surface is small.
            #
            # Some transfer rows additionally carry a small
            # ``Controvalore`` in EUR — that is the previous broker's
            # accrued-coupon adjustment. We emit it as a separate
            # ``coupon`` row so the transfer stays cash-flow-zero on
            # the bank side and the accrual is preserved as a
            # regular distribution.
            quantity = abs(qty_raw)
            bond = looks_like_bond_from_orders(price, quantity)
            denom = 100.0 if bond else 1.0
            transfer_eur = quantity * price / denom / (fx if fx > 0 else 1.0)
            gross_eur = transfer_eur
            net_eur = 0.0
            if abs(gross) > 0.005:
                rows.append({
                    "date": date.strftime("%Y-%m-%d"),
                    "trade_date": trade_date.strftime("%Y-%m-%d"),
                    "type": "coupon",
                    "isin": str(r["Isin"]).strip(),
                    "name": str(r.get("Titolo", "")).strip(),
                    "ticker": "",
                    "quantity": 0.0,
                    "currency": currency,
                    "price_native": "",
                    "fx_rate": fx,
                    "gross_eur": abs(gross),
                    "fees_eur": 0.0,
                    "net_eur": +abs(gross),
                    "source": "fineco",
                })
        else:
            continue

        rows.append({
            "date": date.strftime("%Y-%m-%d"),
            "trade_date": trade_date.strftime("%Y-%m-%d"),
            "type": op_type,
            "isin": str(r["Isin"]).strip(),
            "name": str(r.get("Titolo", "")).strip(),
            "ticker": "",
            "quantity": quantity,
            "currency": currency,
            # ``price_native`` is meaningful for trade and transfer
            # rows (Fineco fills it with the ``Prezzo`` column for
            # both). For coupons / dividends we have only the EUR
            # amount and no per-unit notion, so we leave it blank.
            # ``fx_rate`` follows the same logic.
            "price_native": price if op_type in ("buy", "sell", "transfer_in") else "",
            "fx_rate": fx if op_type in ("buy", "sell", "transfer_in") else "",
            "gross_eur": gross_eur,
            "fees_eur": fees if op_type in ("buy", "sell") else 0.0,
            "net_eur": net_eur,
            "source": "fineco",
        })

    if skipped:
        for key, count in skipped.items():
            logger.warning("Skipped %d row(s) of unsupported kind: %s", count, key)
    return rows


def _backup(path: Path, fineco_dir: Path) -> Optional[Path]:
    """Make a timestamped backup of ``path`` if it exists.

    Backups land alongside the Fineco staging files so personal
    snapshots stay grouped — same convention as ``preprocess_fineco``.
    """
    if not path.exists():
        return None
    fineco_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup = fineco_dir / f"{path.stem}_{stamp}.bak{path.suffix}"
    shutil.copy2(path, backup)
    return backup


def build_orders(fineco_path: Path) -> pd.DataFrame:
    """Build the order-list frame ready to be written as CSV."""
    fineco = _read_fineco_orders(fineco_path)
    rows = _build_rows(fineco)
    if not rows:
        return pd.DataFrame(columns=ORDER_COLUMNS)
    df = pd.DataFrame(rows)
    # Sort oldest-first so the file reads like a journal. Stable
    # sort on a tuple keeps same-day events grouped per ISIN.
    df = df.sort_values(
        by=["date", "isin", "type"], kind="mergesort"
    ).reset_index(drop=True)
    return df[ORDER_COLUMNS]


def _write_orders(df: pd.DataFrame, output: Path) -> None:
    """Write the order frame as CSV, quoting only when needed."""
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        writer.writerow(ORDER_COLUMNS)
        for _, row in df.iterrows():
            writer.writerow([row[col] for col in ORDER_COLUMNS])


def _summary(df: pd.DataFrame, fineco_path: Path) -> str:
    if df.empty:
        return f"0 orders extracted from {fineco_path.name}"
    counts = df["type"].value_counts().to_dict()
    counts_str = ", ".join(f"{k}={v}" for k, v in sorted(counts.items()))
    span = (
        f"{df['date'].min()}..{df['date'].max()}"
        if "date" in df else "—"
    )
    isins = df["isin"].nunique()
    return (
        f"{len(df)} order(s) extracted from {fineco_path.name} · "
        f"{isins} unique ISIN(s) · span {span} · {counts_str}"
    )


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input", default="input/fineco_raw/Lista Titoli.xlsx",
        help="Path to the Fineco 'Lista Titoli' .xlsx export.",
    )
    parser.add_argument(
        "--output", default="input/order_list.csv",
        help="Where to write the resulting order-list CSV.",
    )
    args = parser.parse_args(argv)

    fineco_path = Path(args.input)
    output_path = Path(args.output)

    if not fineco_path.exists():
        logger.error("Fineco movements export not found at %s", fineco_path)
        return 1

    backup = _backup(output_path, fineco_path.parent)
    if backup:
        logger.info("Backed up existing order list to %s", backup)

    df = build_orders(fineco_path)
    _write_orders(df, output_path)

    logger.info("Wrote %s", output_path)
    logger.info(_summary(df, fineco_path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
